### ISSUE TITLE
Create a new version that works with twilio-ruby v5

### ISSUE THREAD

**Issue by philnash** [philnash/twiml_template#4]
`Twilio::TwiML` is no longer based on builder, though still nests in the same way. This shouldn't take too much work.

**Comment by philnash** [comment]
Will need to come up with a way to distinguish between voice and messaging twiml.

Perhaps `.voice_twiml` and `.messaging_twiml` as the extension?

Or maybe just `.vtwiml` and `.mtwiml`.

**Comment by nynhex** [comment]
I'd be happy to help on this.

**Comment by philnash** [comment]
That would be awesome as I've not had the time to think about this yet. Can I guide you in the right direction? Do you have any opinions on the extension used, since we need to distinguish between voice and messaging?

**Comment by philnash** [comment]
I've made a start on this in the [twilio-ruby-v5 branch](https://github.com/philnash/twiml_template/tree/twilio-ruby-v5).

**Comment by kevinjbayer** [comment]
Is there still work remaining to do on this? I've just upgraded to your branch in order to use twilio-ruby and still seems to be working ok. Let me know if I can help in any way to get this over to master and updated on RubyGems. Thanks for your work.

**Comment by philnash** [comment]
To be honest, I'd like feedback on it. I'd be happy to move forward, I just wanted to know that people were using this and that the work I'd done is the direction that works for those using it.

So, if you're using it, what do you think and is there anything you'd change?

**Comment by kevinjbayer** [comment]
Hi Phil,

It works for me, but I use it in a fairly simple capacity right now. Don't really have any feature requests, just thought it'd be nice to upgrade master so people using don't have to jump to another branch.

If I get a chance to work on more features using Twilio, I might have some suggestion then, but for now, the twilio-ruby-v5 branch seems to be doing the trick.

Thanks.

**Comment by philnash** [comment]
Ok, cool. I'll tidy up the branch in the next few days and get it released to rubygems.

**Comment by jamescostian** [comment]
Hi, sorry to bother you, but are there any plans to make a rubygems release with the work on that branch?

**Comment by philnash** [comment]
Ah, sorry, I forgot about this. Will take a look now.

**Comment by philnash** [comment]
Ok, better late then never. I've brought the branch up to date and will ship this as a new major version tomorrow.

**Comment by philnash** [comment]
I have released a [prerelease version 2.0.0.pre](https://rubygems.org/gems/twiml_template/versions/2.0.0.pre). As I'm not using this in production myself, I would love if someone could test this in a real application.

**Comment by kevinjbayer** [comment]
Hi Phil, I'll try to take a look at adding this in to my project over the weekend. I'll let you know if notice any issues. Thanks for your work on this!

**Comment by kevinjbayer** [comment]
Also, (and I apologize, I know this doesn't belong here, but...) I just noticed you're Australian. I'm one of the few Americans who is a HUGE fan of Augie March and I'll sing their praises any chance I get. 🍻

**Comment by jamescostian** [comment]
Thank you @philnash! I've been using e67af05 in production for a while now without any issues. I'll try out 2.0.0.pre

**Comment by philnash** [comment]
OK, I've heard nothing bad in 2 weeks, so this has been released as version 2. When you upgrade, your use of `twiml_template` shouldn't change, but there may be changes in how `twilio-ruby` wants you to generate TwiML. Most obvious are for `message` or `say` which require the message to passed as a named parameter now. For example:

```ruby
twiml.say message: 'Hello!'
```

Any other differences or difficulties, let me know and we can document them as part of the project.
